// nextjs-fullstack/components/reservations/ReservationList.tsx
"use client";
import { useEffect, useState } from "react";
export function ReservationList() {
  const [reservations, setReservations] = useState([]);
  useEffect(() => { fetch("/api/reservations").then(r => r.json()).then(setReservations); }, []);
  return (
    <div>
      <h2 className="text-xl font-bold mb-4">My Reservations</h2>
      {reservations.map((r: any) => (
        <div key={r.id} className="border p-4 rounded mb-2">
          <p>Room: {r.room?.number} | Check-in: {r.checkIn} | Status: <span className="font-semibold">{r.status}</span></p>
        </div>
      ))}
    </div>
  );
}

// rails-vue/frontend/src/components/reservations/ReservationList.vue
<template>
  <div>
    <h2 class="text-xl font-bold mb-4">My Reservations</h2>
    <div v-for="r in reservations" :key="r.id" class="border p-4 rounded mb-2 flex justify-between">
      <span>Room: {{ r.room?.number }} | {{ r.check_in }} → {{ r.check_out }} | {{ r.status }}</span>
      <button v-if="r.status === 'pending'" @click="$emit('cancel', r.id)" class="text-red-500">Cancel</button>
    </div>
  </div>
</template>
<script setup lang="ts">
defineProps<{ reservations: any[] }>();
defineEmits(["cancel"]);
</script>
