// rails-vue/frontend/src/components/rooms/SearchBar.vue
<template>
  <div class="flex gap-4 p-6 bg-white shadow-lg rounded-xl max-w-2xl mx-auto">
    <input type="date" v-model="checkIn" class="flex-1 border p-2 rounded" />
    <input type="date" v-model="checkOut" class="flex-1 border p-2 rounded" />
    <button @click="$emit('search', { check_in: checkIn, check_out: checkOut })" class="bg-blue-600 text-white px-6 rounded">Search</button>
  </div>
</template>
<script setup lang="ts">
import { ref } from "vue";
const checkIn = ref(""); const checkOut = ref("");
defineEmits(["search"]);
</script>

// nextjs-fullstack/components/rooms/SearchBar.tsx
"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function SearchBar() {
  const [checkIn, setCheckIn] = useState("");
  const [checkOut, setCheckOut] = useState("");
  const router = useRouter();
  return (
    <div className="flex gap-4 p-6 bg-white shadow-lg rounded-xl max-w-2xl mx-auto -mt-8 relative z-10">
      <input type="date" value={checkIn} onChange={e => setCheckIn(e.target.value)} className="flex-1 border p-2 rounded" />
      <input type="date" value={checkOut} onChange={e => setCheckOut(e.target.value)} className="flex-1 border p-2 rounded" />
      <button onClick={() => router.push(`/rooms?checkIn=${checkIn}&checkOut=${checkOut}`)} className="bg-blue-600 text-white px-6 rounded">Search</button>
    </div>
  );
}
