// rails-vue/frontend/src/components/rooms/SearchBar.vue
<template>
  <div class="flex gap-4 p-6 bg-white shadow-lg rounded-xl max-w-2xl mx-auto">
    <input type="date" v-model="checkIn" class="flex-1 border p-2 rounded" />
    <input type="date" v-model="checkOut" class="flex-1 border p-2 rounded" />
    <button @click="$emit('search', { check_in: checkIn, check_out: checkOut })" class="bg-blue-600 text-white px-6 rounded">Search</button>
  </div>
</template>
<script setup lang="ts">
import { ref } from "vue";
const checkIn = ref(""); const checkOut = ref("");
defineEmits(["search"]);
</script>

// django-react/frontend/src/components/rooms/SearchBar.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
export function SearchBar() {
  const [checkIn, setCheckIn] = useState("");
  const [checkOut, setCheckOut] = useState("");
  const navigate = useNavigate();
  return (
    <div className="flex gap-4 p-6">
      <input type="date" value={checkIn} onChange={e => setCheckIn(e.target.value)} />
      <input type="date" value={checkOut} onChange={e => setCheckOut(e.target.value)} />
      <button onClick={() => navigate(`/rooms?checkIn=${checkIn}&checkOut=${checkOut}`)}>Search</button>
    </div>
  );
}
