// django-react/frontend/src/components/rooms/RoomFilters.tsx
export function RoomFilters({ onFilter }: { onFilter: (f: any) => void }) {
  return (
    <aside className="w-64">
      <select onChange={e => onFilter({ room_type: e.target.value })}>
        <option value="">All Types</option>
        <option value="SINGLE">Single</option>
        <option value="DOUBLE">Double</option>
        <option value="SUITE">Suite</option>
      </select>
    </aside>
  );
}

// rails-vue/frontend/src/components/rooms/RoomFilters.vue
<template>
  <aside class="w-64">
    <h2 class="font-bold mb-4">Filters</h2>
    <select @change="$emit('filter', { room_type: ($event.target as HTMLSelectElement).value })" class="w-full border p-2">
      <option value="">All Types</option>
      <option value="single">Single</option>
      <option value="double">Double</option>
      <option value="suite">Suite</option>
    </select>
  </aside>
</template>
<script setup lang="ts">
defineEmits(["filter"]);
</script>
