// nextjs-fullstack/components/rooms/RoomFilters.tsx
"use client";
import { useRoomStore } from "@/store/roomStore";
export function RoomFilters() {
  const { filters, setFilters } = useRoomStore();
  return (
    <aside className="w-64">
      <h2 className="font-bold mb-4">Filters</h2>
      <select onChange={e => setFilters({ ...filters, type: e.target.value })} className="w-full border p-2">
        <option value="">All Types</option>
        <option value="SINGLE">Single</option>
        <option value="DOUBLE">Double</option>
        <option value="SUITE">Suite</option>
      </select>
    </aside>
  );
}

// rails-vue/frontend/src/components/rooms/RoomFilters.vue
<template>
  <aside class="w-64">
    <h2 class="font-bold mb-4">Filters</h2>
    <select @change="$emit('filter', { room_type: ($event.target as HTMLSelectElement).value })" class="w-full border p-2">
      <option value="">All Types</option>
      <option value="single">Single</option>
      <option value="double">Double</option>
      <option value="suite">Suite</option>
    </select>
  </aside>
</template>
<script setup lang="ts">
defineEmits(["filter"]);
</script>
